In [1]:
print("Hello World!")

Hello World!

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from collections import Counter
import plotly.express as px
from sklearn.cluster import DBSCAN

In [7]:
# Load Excel file
excel_file_path = r"C:\Desktop\UB Retail Data Insights\UB-Tableau-Assignment_and-DataSet-Only.xlsx"  
excel_data = pd.ExcelFile(excel_file_path)

In [8]:
# Load sheet into a separate DataFrame
retail = excel_data.parse(sheet_name='data-set')

In [10]:
retail.describe().T

,count,mean,min,25%,50%,75%,max,std
full_date,244000,2022-07-19 12:00:00.000000256,2022-01-01 00:00:00,2022-04-10 18:00:00,2022-07-19 12:00:00,2022-10-27 06:00:00,2023-02-04 00:00:00,NaN
year_num,244000.0,2022.085,2021.0,2022.0,2022.0,2022.0,2023.0,0.287707
weeks_in_following_year,244000.0,52.0,52.0,52.0,52.0,52.0,52.0,0.0
full_date_year_num,244000.0,2022.0875,2022.0,2022.0,2022.0,2022.0,2023.0,0.282567
weeks_in_year,244000.0,52.0025,52.0,52.0,52.0,52.0,53.0,0.049938
week_num,244000.0,24.5075,1.0,10.0,24.0,38.0,52.0,15.847112
month_num,244000.0,6.0525,1.0,3.0,6.0,9.0,12.0,3.632464
month_day_num,244000.0,15.61,1.0,8.0,16.0,23.0,31.0,8.863308
year_day_num,244000.0,168.5625,1.0,65.75,165.5,265.25,365.0,110.965294
quarter_num,244000.0,2.3775,1.0,1.0,2.0,3.0,4.0,1.148912
rank_within_cohort,244000.0,1.308197,1.0,1.0,1.0,2.0,2.0,0.461749
daily_revenue_usd,135614.0,155.998984,0.0,0.0,29.98,129.5575,45058.7,655.821333
daily_units_sold,135614.0,7.915754,0.0,0.0,1.0,5.0,3011.0,42.159182
ppc_sales,135614.0,45.343195,0.0,0.0,0.32,9.73,13987.93,258.533286
ppc_cost,135614.0,-13.913117,-3351.69,-4.22,-0.26,0.0,0.0,73.859611
orders,135614.0,7.566247,0.0,0.0,1.0,5.0,2988.0,41.581978
cogs,135614.0,-34.580208,-8681.82,-30.42,-5.72,0.0,0.0,131.943093
fbafees,135614.0,-60.810347,-18211.92,-48.88,-10.73,0.0,0.0,260.856851
promo_amount,135614.0,-5.036736,-2378.05,-2.0,0.0,0.0,0.0,37.006069
contribution_margin,135614.0,37.566079,-1876.45,-0.26,0.49,32.29,15253.66,175.956754
referralfees,135614.0,-22.332452,-6614.45,-18.57,-4.2,0.0,0.0,92.819144
fba_fulfillment_fees,135614.0,-37.571106,-10930.38,-30.1075,-5.59,0.0,0.0,162.290536
promo_units,135614.0,2.474663,0.0,0.0,0.0,1.0,1435.0,21.683708
shipped,135614.0,7.89917,0.0,0.0,1.0,5.0,3011.0,42.127865
ret_date_return_amount_usd,135614.0,-4.224776,-615.77,0.0,0.0,0.0,0.0,18.217489
ret_date_return_promo_amount_usd,135614.0,0.136477,0.0,0.0,0.0,0.0,61.2,1.189587
ret_date_return_quantity,135614.0,155.998984,0.0,0.0,29.98,129.5575,45058.7,655.821333
returned_units,135614.0,0.199294,0.0,0.0,0.0,0.0,58.0,1.050391
return_usd,135614.0,-3.926968,-868.24,0.0,0.0,0.0,0.0,17.984302
ops_net_tax,135614.0,155.998984,0.0,0.0,29.98,129.5575,45058.7,655.821333

In [11]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244000 entries, 0 to 243999
Data columns (total 40 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   full_date                         244000 non-null  datetime64[ns]
 1   year_num                          244000 non-null  int64
 2   weeks_in_following_year           244000 non-null  int64
 3   full_date_year_num                244000 non-null  int64
 4   weeks_in_year                     244000 non-null  int64
 5   week_num                          244000 non-null  int64
 6   month_num                         244000 non-null  int64
 7   month_day_num                     244000 non-null  int64
 8   year_day_num                      244000 non-null  int64
 9   quarter_num                       244000 non-null  int64
 10  month_name                        244000 non-null  object
 11  month_name_short                  244000 non-null  object
 12  day_name                          244000 non-null  object
 13  Brand                             244000 non-null  object
 14  cohort                            244000 non-null  object
 15  rank_within_cohort                244000 non-null  int64
 16  divison                           244000 non-null  object
 17  category                          244000 non-null  object
 18  product_group                     243600 non-null  object
 19  Product                           244000 non-null  object
 20  marketplace                       244000 non-null  object
 21  daily_revenue_usd                 135614 non-null  float64
 22  daily_units_sold                  135614 non-null  float64
 23  ppc_sales                         135614 non-null  float64
 24  ppc_cost                          135614 non-null  float64
 25  orders                            135614 non-null  float64
 26  cogs                              135614 non-null  float64
 27  fbafees                           135614 non-null  float64
 28  promo_amount                      135614 non-null  float64
 29  contribution_margin               135614 non-null  float64
 30  referralfees                      135614 non-null  float64
 31  fba_fulfillment_fees              135614 non-null  float64
 32  promo_units                       135614 non-null  float64
 33  shipped                           135614 non-null  float64
 34  ret_date_return_amount_usd        135614 non-null  float64
 35  ret_date_return_promo_amount_usd  135614 non-null  float64
 36  ret_date_return_quantity          135614 non-null  float64
 37  returned_units                    135614 non-null  float64
 38  return_usd                        135614 non-null  float64
 39  ops_net_tax                       135614 non-null  float64
dtypes: datetime64[ns](1), float64(19), int64(10), object(10)
memory usage: 74.5+ MB

In [15]:
retail.isnull().sum()

full_date                                0
year_num                                 0
weeks_in_following_year                  0
full_date_year_num                       0
weeks_in_year                            0
week_num                                 0
month_num                                0
month_day_num                            0
year_day_num                             0
quarter_num                              0
month_name                               0
month_name_short                         0
day_name                                 0
Brand                                    0
cohort                                   0
rank_within_cohort                       0
divison                                  0
category                                 0
product_group                          400
Product                                  0
marketplace                              0
daily_revenue_usd                   108386
daily_units_sold                    108386
ppc_sales                           108386
ppc_cost                            108386
orders                              108386
cogs                                108386
fbafees                             108386
promo_amount                        108386
contribution_margin                 108386
referralfees                        108386
fba_fulfillment_fees                108386
promo_units                         108386
shipped                             108386
ret_date_return_amount_usd          108386
ret_date_return_promo_amount_usd    108386
ret_date_return_quantity            108386
returned_units                      108386
return_usd                          108386
ops_net_tax                         108386
dtype: int64

In [18]:
retail.duplicated().sum()

0

In [20]:
import pandas as pd

# List of desired columns
columns_to_keep = [
    'full_date', 'full_date_year_num', 'month_num', 'month_day_num', 
    'quarter_num', 'Brand', 'divison', 'category', 'Product', 
    'marketplace', 'daily_revenue_usd', 'daily_units_sold', 'ppc_sales', 
    'ppc_cost', 'orders', 'cogs', 'fbafees', 'promo_amount', 
    'contribution_margin', 'referralfees', 'fba_fulfillment_fees', 
    'promo_units', 'shipped', 'ret_date_return_amount_usd', 
    'ret_date_return_promo_amount_usd', 'ret_date_return_quantity', 
    'returned_units', 'return_usd', 'ops_net_tax'
]

# Create a new DataFrame with only the specified columns
retail_filtered =retail[columns_to_keep]

In [21]:
retail_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244000 entries, 0 to 243999
Data columns (total 29 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   full_date                         244000 non-null  datetime64[ns]
 1   full_date_year_num                244000 non-null  int64
 2   month_num                         244000 non-null  int64
 3   month_day_num                     244000 non-null  int64
 4   quarter_num                       244000 non-null  int64
 5   Brand                             244000 non-null  object
 6   divison                           244000 non-null  object
 7   category                          244000 non-null  object
 8   Product                           244000 non-null  object
 9   marketplace                       244000 non-null  object
 10  daily_revenue_usd                 135614 non-null  float64
 11  daily_units_sold                  135614 non-null  float64
 12  ppc_sales                         135614 non-null  float64
 13  ppc_cost                          135614 non-null  float64
 14  orders                            135614 non-null  float64
 15  cogs                              135614 non-null  float64
 16  fbafees                           135614 non-null  float64
 17  promo_amount                      135614 non-null  float64
 18  contribution_margin               135614 non-null  float64
 19  referralfees                      135614 non-null  float64
 20  fba_fulfillment_fees              135614 non-null  float64
 21  promo_units                       135614 non-null  float64
 22  shipped                           135614 non-null  float64
 23  ret_date_return_amount_usd        135614 non-null  float64
 24  ret_date_return_promo_amount_usd  135614 non-null  float64
 25  ret_date_return_quantity          135614 non-null  float64
 26  returned_units                    135614 non-null  float64
 27  return_usd                        135614 non-null  float64
 28  ops_net_tax                       135614 non-null  float64
dtypes: datetime64[ns](1), float64(19), int64(4), object(5)
memory usage: 54.0+ MB

In [22]:
import pandas as pd
import numpy as np

# List of columns with blanks
columns_with_blanks = [
    'daily_revenue_usd', 'daily_units_sold', 'ppc_sales', 'ppc_cost', 'orders',
    'cogs', 'fbafees', 'promo_amount', 'contribution_margin', 'referralfees',
    'fba_fulfillment_fees', 'promo_units', 'shipped', 'ret_date_return_amount_usd',
    'ret_date_return_promo_amount_usd', 'ret_date_return_quantity', 'returned_units',
    'return_usd', 'ops_net_tax'
]

# Create a flag column to indicate rows that had blanks(no values)(1 is True,, 0 is False)
retail_filtered['had_blanks'] = retail_filtered[columns_with_blanks].isnull().any(axis=1).astype(int)

# Fill blanks with zeros to ensure data integrity
retail_filtered[columns_with_blanks] = retail_filtered[columns_with_blanks].fillna(0)

# Print summary to verify
#print(f"Rows with originally blank values: {retail_filtered['had_blanks'].sum()}")
#print(f"Percentage of rows with filled blanks: {retail_filtered['had_blanks'].mean()*100:.2f}%")

C:\Users\godwi\AppData\Local\Temp\ipykernel_9752\2549327034.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_filtered['had_blanks'] = retail_filtered[columns_with_blanks].isnull().any(axis=1).astype(int)
C:\Users\godwi\AppData\Local\Temp\ipykernel_9752\2549327034.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_filtered[columns_with_blanks] = retail_filtered[columns_with_blanks].fillna(0)

In [ ]:
retail_filtered.info()

In [25]:
retail_filtered.tail(3)

,full_date,full_date_year_num,month_num,month_day_num,quarter_num,Brand,divison,category,Product,marketplace,...,fba_fulfillment_fees,promo_units,shipped,ret_date_return_amount_usd,ret_date_return_promo_amount_usd,ret_date_return_quantity,returned_units,return_usd,ops_net_tax,had_blanks
243997,2022-08-25,2022,8,25,3,VNS,Hard Goods,Gifting,D0DRT7N9LZ,US,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
243998,2022-09-27,2022,9,27,3,VNS,Hard Goods,Gifting,D0DRT7N9LZ,US,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
243999,2022-08-24,2022,8,24,3,VNS,Hard Goods,Gifting,D0DRT7N9LZ,US,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [26]:
retail_filtered.describe().T

,count,mean,min,25%,50%,75%,max,std
full_date,244000,2022-07-19 12:00:00.000000256,2022-01-01 00:00:00,2022-04-10 18:00:00,2022-07-19 12:00:00,2022-10-27 06:00:00,2023-02-04 00:00:00,NaN
full_date_year_num,244000.0,2022.0875,2022.0,2022.0,2022.0,2022.0,2023.0,0.282567
month_num,244000.0,6.0525,1.0,3.0,6.0,9.0,12.0,3.632464
month_day_num,244000.0,15.61,1.0,8.0,16.0,23.0,31.0,8.863308
quarter_num,244000.0,2.3775,1.0,1.0,2.0,3.0,4.0,1.148912
daily_revenue_usd,244000.0,86.703468,0.0,0.0,0.0,42.1475,45058.7,495.031079
daily_units_sold,244000.0,4.399537,0.0,0.0,0.0,2.0,3011.0,31.675462
ppc_sales,244000.0,25.201525,0.0,0.0,0.0,0.74,13987.93,194.05289
ppc_cost,244000.0,-7.732842,-3351.69,-0.5,0.0,0.0,0.0,55.495749
orders,244000.0,4.205283,0.0,0.0,0.0,2.0,2988.0,31.22714
cogs,244000.0,-19.21951,-8681.82,-8.98,0.0,0.0,0.0,99.854994
fbafees,244000.0,-33.798092,-18211.92,-15.21,0.0,0.0,0.0,196.806096
promo_amount,244000.0,-2.799393,-2378.05,0.0,0.0,0.0,0.0,27.701874
contribution_margin,244000.0,20.879042,-1876.45,0.0,0.0,5.74,15253.66,132.499824
referralfees,244000.0,-12.412267,-6614.45,-6.0,0.0,0.0,0.0,70.082167
fba_fulfillment_fees,244000.0,-20.881836,-10930.38,-9.04,0.0,0.0,0.0,122.421845
promo_units,244000.0,1.375406,0.0,0.0,0.0,0.0,1435.0,16.212236
shipped,244000.0,4.39032,0.0,0.0,0.0,2.0,3011.0,31.651272
ret_date_return_amount_usd,244000.0,-2.348109,-615.77,0.0,0.0,0.0,0.0,13.742692
ret_date_return_promo_amount_usd,244000.0,0.075853,0.0,0.0,0.0,0.0,61.2,0.889444
ret_date_return_quantity,244000.0,86.703468,0.0,0.0,0.0,42.1475,45058.7,495.031079
returned_units,244000.0,0.110766,0.0,0.0,0.0,0.0,58.0,0.789319
return_usd,244000.0,-2.18259,-868.24,0.0,0.0,0.0,0.0,13.548813
ops_net_tax,244000.0,86.703468,0.0,0.0,0.0,42.1475,45058.7,495.031079
had_blanks,244000.0,0.444205,0.0,0.0,0.0,1.0,1.0,0.496878

In [27]:
import pandas as pd

#Create a new column 'flagged_row_for_ppc_sales>0' with True for rows meeting our criteria(when ppc_sales >0 & ppc_cost<0 &contribution_margin<0) and False otherwise.

retail_filtered['flagged_row_for_ppc_sales>0'] = ((retail_filtered['daily_revenue_usd'] == 0) & 
                     (retail_filtered['daily_units_sold'] == 0) & 
                     (retail_filtered['orders'] == 0) & 
                     ((retail_filtered['ppc_sales'] > 0) | (retail_filtered['ppc_cost'] < 0) | (retail_filtered['contribution_margin'] < 0)))

# Now we can see how many rows are flagged
#flagged_count = retail_filtered['flagged_row_for_ppc_sales>0'].sum()
#total_rows = len(retail_filtered)
#percentage_flagged = (flagged_count / total_rows) * 100

#print(f"Number of flagged rows: {flagged_count}")
#print(f"Percentage of flagged rows: {percentage_flagged:.2f}%")

C:\Users\godwi\AppData\Local\Temp\ipykernel_9752\1163620924.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_filtered['flagged_row_for_ppc_sales>0'] = ((retail_filtered['daily_revenue_usd'] == 0) &

In [28]:
retail_filtered.head(2)

,full_date,full_date_year_num,month_num,month_day_num,quarter_num,Brand,divison,category,Product,marketplace,...,promo_units,shipped,ret_date_return_amount_usd,ret_date_return_promo_amount_usd,ret_date_return_quantity,returned_units,return_usd,ops_net_tax,had_blanks,flagged_row_for_ppc_sales>0
0,2022-05-24,2022,5,24,2,VNS,Hard Goods,Gifting,D073WXTV1H,US,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,True
1,2022-04-21,2022,4,21,2,VNS,Hard Goods,Gifting,D073WXTV1H,US,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,True

In [ ]:
retail_filtered.info()

In [32]:
# Export DataFrame to CSV
#retail_filtered.to_csv("retail_clean.csv", index=False)